import { strict as assert } from 'node:assert';
import { KEY, applyWorldOverrides } from '../core.mjs';
import { SCOPED_KEY, migrateScopes, readScopedState, writeScopedState } from '../scopes.mjs';
import { createActivationTracker } from '../activation.mjs';

const settings = {}, a = {}, b = {}, other = {};
const p = { kind: 'prompt', source: 'P', id: 'main', name: 'Main', state: false };
const w = { kind: 'world', source: 'Book', id: '1', name: 'Lore', state: false, activation: 'constant' };
const read = (metadata, owner = 'Alice', preset = 'P') => readScopedState(settings, metadata, owner, preset);
migrateScopes(settings, a, 'Alice', 'P');
writeScopedState(settings, a, 'Alice', 'P', { version: 1, items: [p, w] });
migrateScopes(settings, b, 'Alice', 'P');
assert.equal(read(b).items[0].state, false, 'preset ON/OFF shared across chats');
assert.equal(read(b).items[1].state, null, 'new chat follows native WI toggle');
assert.equal(read(b).items[1].activation, null, 'new chat follows native WI mode');
assert.equal(read(a).items[1].state, false, 'previous chat retains its override');
migrateScopes(settings, other, 'Bob', 'P');
assert.equal(read(other, 'Bob').items.length, 1, 'WI registry isolated by character');
assert.equal(read(other, 'Bob').items[0].state, false, 'same preset shared across characters');
migrateScopes(settings, a, 'Alice', 'Q');
assert.ok(read(a, 'Alice', 'Q').items.every(x => x.kind === 'world'), 'preset isolation');
const original = { world: 'Book', uid: 1, disable: true, constant: false };
const payload = { globalLore: [original] };
applyWorldOverrides(payload, read(b));
assert.equal(payload.globalLore[0].disable, true, 'unmodified chat uses actual native state');
assert.equal(original.constant, false, 'source preserved');
const removed = read(a); removed.items = removed.items.filter(x => x.kind !== 'world');
writeScopedState(settings, a, 'Alice', 'P', removed);
assert.ok(read(b).items.every(x => x.kind === 'prompt'), 'registry removal shared, stale overrides ignored');

const legacySettings = { state: { version: 1, items: [p, w] } };
const legacyChat = { [KEY]: { version: 1, items: [{ ...p, state: true }, { ...w, state: true }] } };
const backup = JSON.stringify(legacyChat[KEY]);
assert.equal(migrateScopes(legacySettings, legacyChat, 'Alice', 'P'), true);
assert.equal(readScopedState(legacySettings, legacyChat, 'Alice', 'P').items[0].state, true);
assert.equal(migrateScopes(legacySettings, legacyChat, 'Alice', 'P'), false, 'migration idempotent');
assert.equal(JSON.stringify(legacyChat[KEY]), backup, 'legacy backup retained');
const fresh = {};
migrateScopes(legacySettings, fresh, 'Alice', 'P');
assert.equal(readScopedState(legacySettings, fresh, 'Alice', 'P').items[1].state, null, 'old global toggles do not leak into new chats');
assert.equal(fresh[SCOPED_KEY].world.items.length, 0);
const cleared = { version: 1, items: [] };
writeScopedState(legacySettings, legacyChat, 'Alice', 'P', cleared);
migrateScopes(legacySettings, legacyChat, 'Alice', 'P');
assert.equal(readScopedState(legacySettings, legacyChat, 'Alice', 'P').items.length, 0, 'removed entries stay removed after migration');

const tracker = createActivationTracker();
assert.equal(tracker.result.phase, 'unknown');
tracker.begin('A'); tracker.finish('A');
assert.equal(tracker.result.phase, 'unknown', 'early failure is not zero');
tracker.begin('A'); tracker.prepared('A'); tracker.finish('A');
assert.equal(tracker.result.phase, 'ready'); assert.equal(tracker.result.entries.length, 0);
tracker.begin('A');
const entry = { world: 'Book', uid: 1, comment: 'Lore', content: 'DO NOT CACHE', constant: true };
tracker.capture('A', [entry, entry]);
assert.equal(tracker.result.entries.length, 1, 'deduplicate book + ID');
assert.ok(!JSON.stringify(tracker.result).includes('DO NOT CACHE'));
entry.comment = 'changed'; assert.equal(tracker.result.entries[0].name, 'Lore');
tracker.finish('A'); tracker.capture('A', []);
assert.equal(tracker.result.entries.length, 1, 'late event ignored');
tracker.reset(); tracker.capture('A', [entry]);
assert.equal(tracker.result.phase, 'unknown', 'chat change discards result');
tracker.begin('B'); tracker.capture('A', [entry]);
assert.equal(tracker.result.entries.length, 0, 'other chat ignored');
console.log('PASS: preset/character/chat scopes, migration, native defaults, deletion, activation zero/failure/reset and minimal snapshots');
